/**
 * GENERATED by scripts/gen-country-fleet.mjs from scripts/country-fleet.json —
 * DO NOT EDIT. Quantity definitions, per-row citations, and the
 * ownership→traffic derivation are documented in the JSON.
 *
 * Fallback local-road vehicle mix + residential trip generation for the
 * service-tree heuristic. This is NOT a global split SSOT: national censuses
 * (measured, provenance rank ≥ 6) keep their own source-specific splits.
 */

export interface CountryFleet {
  /** Share of powered 2-/3-wheelers in daily local-road vehicle flow. */
  motoTrafficShare: number
  /** Motor-vehicle trips per STOCK dwelling per day, both directions —
   *  survey per-household values are ×0.92 occupancy-folded at generation,
   *  matching the GFA-estimated stock dwellings the trip model multiplies. */
  tripsPerDwelling: number
}

/** Terminal of the cascade — the pre-2026-07 service-tree constants. Medium/
 *  heavy local-road shares stay world-constant (no per-country signal):
 *  medium 0.01, heavy 0.02 (see splitAADT). */
export const WORLD_FLEET: CountryFleet = {
  motoTrafficShare: 0.01,
  tripsPerDwelling: 3.68,
}

const COUNTRY_FLEET: Record<string, CountryFleet> = {
  AD: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  AE: { motoTrafficShare: 0.011, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0264 (WHO 2021); tpd Asia band ×0.92 occ
  AF: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  AG: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.0188 (WHO 2021); tpd North America band ×0.92 occ
  AI: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  AL: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0605 (WHO 2021); tpd Europe band ×0.92 occ
  AM: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  AO: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  AQ: { motoTrafficShare: 0.01, tripsPerDwelling: 3.68 }, // WORLD; tpd WORLD
  AR: { motoTrafficShare: 0.07, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.3476 (WHO 2021); tpd South America band ×0.92 occ
  AS: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  AT: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  AU: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0454 (WHO 2021); tpd Oceania band ×0.92 occ
  AW: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  AX: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  AZ: { motoTrafficShare: 0.01, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0033 (WHO 2021); tpd Asia band ×0.92 occ
  BA: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0165 (WHO 2021); tpd Europe band ×0.92 occ
  BB: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  BD: { motoTrafficShare: 0.305, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.7624 (WHO 2021); tpd Asia band ×0.92 occ
  BE: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0678 (WHO 2021); tpd Europe band ×0.92 occ
  BF: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  BG: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0597 (WHO 2021); tpd Europe band ×0.92 occ
  BH: { motoTrafficShare: 0.013, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0318 (WHO 2021); tpd Asia band ×0.92 occ
  BI: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  BJ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  BL: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  BM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  BN: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  BO: { motoTrafficShare: 0.059, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.2954 (WHO 2021); tpd South America band ×0.92 occ
  BR: { motoTrafficShare: 0.054, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.2714 (WHO 2021); tpd South America band ×0.92 occ
  BS: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  BT: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  BW: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  BY: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  BZ: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  CA: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.0311 (WHO 2021); tpd North America band ×0.92 occ
  CD: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  CF: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  CG: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  CH: { motoTrafficShare: 0.018, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.1221 (WHO 2021); tpd Europe band ×0.92 occ
  CI: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  CK: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  CL: { motoTrafficShare: 0.01, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.0391 (WHO 2021); tpd South America band ×0.92 occ
  CM: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  CN: { motoTrafficShare: 0.05, tripsPerDwelling: 1.38 }, // calibrated override; tpd curated ×0.92 occ
  CO: { motoTrafficShare: 0.122, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.6097 (WHO 2021); tpd South America band ×0.92 occ
  CR: { motoTrafficShare: 0.043, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.2874 (WHO 2021); tpd North America band ×0.92 occ
  CU: { motoTrafficShare: 0.058, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.3859 (WHO 2021); tpd North America band ×0.92 occ
  CV: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  CW: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  CY: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  CZ: { motoTrafficShare: 0.03, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.2 (WHO 2021); tpd Europe band ×0.92 occ
  DE: { motoTrafficShare: 0.012, tripsPerDwelling: 3.59 }, // 0.15 x ownership 0.0772 (WHO 2021); tpd curated ×0.92 occ
  DJ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  DK: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  DM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  DO: { motoTrafficShare: 0.084, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.5579 (WHO 2021); tpd North America band ×0.92 occ
  DZ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  EC: { motoTrafficShare: 0.057, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.2849 (WHO 2021); tpd South America band ×0.92 occ
  EE: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  EG: { motoTrafficShare: 0.18, tripsPerDwelling: 1.84 }, // calibrated override; tpd curated ×0.92 occ
  EH: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  ER: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  ES: { motoTrafficShare: 0.024, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.157 (WHO 2021); tpd Europe band ×0.92 occ
  ET: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  FI: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0626 (WHO 2021); tpd Europe band ×0.92 occ
  FJ: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  FK: { motoTrafficShare: 0.06, tripsPerDwelling: 2.02 }, // South America band; tpd South America band ×0.92 occ
  FM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  FO: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  FR: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0633 (WHO 2021); tpd Europe band ×0.92 occ
  GA: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  GB: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0337 (WHO 2021); tpd Europe band ×0.92 occ
  GD: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  GE: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  GG: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  GH: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  GI: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  GL: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  GM: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  GN: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  GQ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  GR: { motoTrafficShare: 0.029, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.1907 (WHO 2021); tpd Europe band ×0.92 occ
  GS: { motoTrafficShare: 0.01, tripsPerDwelling: 3.68 }, // WORLD; tpd WORLD
  GT: { motoTrafficShare: 0.066, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.4386 (WHO 2021); tpd North America band ×0.92 occ
  GU: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  GW: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  GY: { motoTrafficShare: 0.06, tripsPerDwelling: 2.02 }, // South America band; tpd South America band ×0.92 occ
  HK: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  HM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.68 }, // WORLD; tpd WORLD
  HN: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  HR: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0608 (WHO 2021); tpd Europe band ×0.92 occ
  HT: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  HU: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0415 (WHO 2021); tpd Europe band ×0.92 occ
  ID: { motoTrafficShare: 0.331, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.8266 (WHO 2021); tpd Asia band ×0.92 occ
  IE: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  IL: { motoTrafficShare: 0.016, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0407 (WHO 2021); tpd Asia band ×0.92 occ
  IM: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  IN: { motoTrafficShare: 0.3, tripsPerDwelling: 0.92 }, // calibrated override; tpd curated ×0.92 occ
  IO: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  IQ: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  IR: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  IS: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0448 (WHO 2021); tpd Europe band ×0.92 occ
  IT: { motoTrafficShare: 0.028, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.1873 (WHO 2021); tpd Europe band ×0.92 occ
  JE: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  JM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  JO: { motoTrafficShare: 0.01, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0079 (WHO 2021); tpd Asia band ×0.92 occ
  JP: { motoTrafficShare: 0.02, tripsPerDwelling: 2.3 }, // calibrated override; tpd curated ×0.92 occ
  KE: { motoTrafficShare: 0.2, tripsPerDwelling: 1.38 }, // calibrated override; tpd curated ×0.92 occ
  KG: { motoTrafficShare: 0.01, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0064 (WHO 2021); tpd Asia band ×0.92 occ
  KH: { motoTrafficShare: 0.3, tripsPerDwelling: 2.3 }, // calibrated override; tpd curated ×0.92 occ
  KI: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  KM: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  KN: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  KP: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  KR: { motoTrafficShare: 0.03, tripsPerDwelling: 2.67 }, // calibrated override; tpd curated ×0.92 occ
  KW: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  KY: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  KZ: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  LA: { motoTrafficShare: 0.3, tripsPerDwelling: 2.3 }, // calibrated override; tpd curated ×0.92 occ
  LB: { motoTrafficShare: 0.032, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0803 (WHO 2021); tpd Asia band ×0.92 occ
  LC: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  LI: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  LK: { motoTrafficShare: 0.289, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.7216 (WHO 2021); tpd Asia band ×0.92 occ
  LR: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  LS: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  LT: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  LU: { motoTrafficShare: 0.018, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.1169 (WHO 2021); tpd Europe band ×0.92 occ
  LV: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0324 (WHO 2021); tpd Europe band ×0.92 occ
  LY: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MA: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MC: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  MD: { motoTrafficShare: 0.031, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.2055 (WHO 2021); tpd Europe band ×0.92 occ
  ME: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0246 (WHO 2021); tpd Europe band ×0.92 occ
  MF: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  MG: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MH: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  MK: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0287 (WHO 2021); tpd Europe band ×0.92 occ
  ML: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MM: { motoTrafficShare: 0.3, tripsPerDwelling: 2.3 }, // calibrated override; tpd curated ×0.92 occ
  MN: { motoTrafficShare: 0.023, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0581 (WHO 2021); tpd Asia band ×0.92 occ
  MO: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  MP: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  MR: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MS: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  MT: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  MU: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MV: { motoTrafficShare: 0.349, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.8719 (WHO 2021); tpd Asia band ×0.92 occ
  MW: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  MX: { motoTrafficShare: 0.017, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.1118 (WHO 2021); tpd North America band ×0.92 occ
  MY: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  MZ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  NA: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  NC: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  NE: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  NF: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  NG: { motoTrafficShare: 0.3, tripsPerDwelling: 1.38 }, // calibrated override; tpd curated ×0.92 occ
  NI: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  NL: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  NO: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  NP: { motoTrafficShare: 0.317, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.7927 (WHO 2021); tpd Asia band ×0.92 occ
  NR: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  NU: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  NZ: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0351 (WHO 2021); tpd Oceania band ×0.92 occ
  OM: { motoTrafficShare: 0.01, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0045 (WHO 2021); tpd Asia band ×0.92 occ
  PA: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  PE: { motoTrafficShare: 0.117, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.5855 (WHO 2021); tpd South America band ×0.92 occ
  PF: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  PG: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  PH: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  PK: { motoTrafficShare: 0.318, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.7957 (WHO 2021); tpd Asia band ×0.92 occ
  PL: { motoTrafficShare: 0.014, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0931 (WHO 2021); tpd Europe band ×0.92 occ
  PM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  PN: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  PR: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  PS: { motoTrafficShare: 0.01, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.0092 (WHO 2021); tpd Asia band ×0.92 occ
  PT: { motoTrafficShare: 0.011, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0707 (WHO 2021); tpd Europe band ×0.92 occ
  PW: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  PY: { motoTrafficShare: 0.072, tripsPerDwelling: 2.02 }, // 0.2 x ownership 0.362 (WHO 2021); tpd South America band ×0.92 occ
  QA: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  RO: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  RS: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  RU: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0387 (WHO 2021); tpd Europe band ×0.92 occ
  RW: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SA: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  SB: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  SC: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SD: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SE: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0631 (WHO 2021); tpd Europe band ×0.92 occ
  SG: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  SH: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SI: { motoTrafficShare: 0.012, tripsPerDwelling: 3.4 }, // 0.15 x ownership 0.0827 (WHO 2021); tpd Europe band ×0.92 occ
  SK: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  SL: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SM: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  SN: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SO: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SR: { motoTrafficShare: 0.06, tripsPerDwelling: 2.02 }, // South America band; tpd South America band ×0.92 occ
  SS: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  ST: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  SV: { motoTrafficShare: 0.044, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.2925 (WHO 2021); tpd North America band ×0.92 occ
  SX: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  SY: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  SZ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  TC: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  TD: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  TF: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  TG: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  TH: { motoTrafficShare: 0.2, tripsPerDwelling: 2.3 }, // calibrated override; tpd curated ×0.92 occ
  TJ: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  TL: { motoTrafficShare: 0.31, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.7739 (WHO 2021); tpd Asia band ×0.92 occ
  TM: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  TN: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  TO: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  TR: { motoTrafficShare: 0.059, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.1483 (WHO 2021); tpd Asia band ×0.92 occ
  TT: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  TV: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  TW: { motoTrafficShare: 0.35, tripsPerDwelling: 2.3 }, // calibrated override; tpd curated ×0.92 occ
  TZ: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  UA: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  UG: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  UM: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  US: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // 0.15 x ownership 0.0303 (WHO 2020); tpd curated ×0.92 occ
  UY: { motoTrafficShare: 0.06, tripsPerDwelling: 2.02 }, // South America band; tpd South America band ×0.92 occ
  UZ: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  VA: { motoTrafficShare: 0.02, tripsPerDwelling: 3.4 }, // Europe band; tpd Europe band ×0.92 occ
  VC: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  VE: { motoTrafficShare: 0.06, tripsPerDwelling: 2.02 }, // South America band; tpd South America band ×0.92 occ
  VG: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  VI: { motoTrafficShare: 0.01, tripsPerDwelling: 3.22 }, // North America band; tpd North America band ×0.92 occ
  VN: { motoTrafficShare: 0.372, tripsPerDwelling: 2.3 }, // 0.4 x ownership 0.9305 (WHO 2021); tpd Asia band ×0.92 occ
  VU: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  WF: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  WS: { motoTrafficShare: 0.01, tripsPerDwelling: 3.4 }, // Oceania band; tpd Oceania band ×0.92 occ
  YE: { motoTrafficShare: 0.15, tripsPerDwelling: 2.3 }, // Asia band; tpd Asia band ×0.92 occ
  ZA: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  ZM: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
  ZW: { motoTrafficShare: 0.1, tripsPerDwelling: 1.38 }, // Africa band; tpd Africa band ×0.92 occ
}

/** Country → fleet row; unknown/missing ISO falls to WORLD_FLEET (continent
 *  bands are resolved into the per-country rows at generation time). */
export function fleetForIso(iso2: string | undefined): CountryFleet {
  return (iso2 !== undefined && COUNTRY_FLEET[iso2]) || WORLD_FLEET
}
