/**
 * Generate `engine/noise-compute/src/sources.rs` from `pipeline/lib/sources.ts`.
 *
 * Single source of truth for dataset metadata is the TypeScript registry.
 * This script produces the Rust mirror that the engine compiles in — no
 * `build.rs` → `npx tsx` chain (plan v5 /gg W: keep Rust builds pure Rust).
 *
 * Workflow: edit `sources.ts` → run `npm run gen:sources` (from pipeline/)
 * → commit both files together. Pre-commit hook may check the two stay in
 * sync.
 *
 * Usage:
 *   cd pipeline && npx tsx lib/gen-sources-rs.ts
 *   # or
 *   cd pipeline && npm run gen:sources
 */

import { writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { SOURCES, type Provenance } from './sources.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const OUTPUT_PATH = resolve(__dirname, '../../engine/noise-compute/src/sources.rs')

const PROVENANCE_TO_RUST: Record<Provenance, string> = {
  'national-measured': 'Provenance::NationalMeasured',
  'continental-measured': 'Provenance::ContinentalMeasured',
  'global-measured': 'Provenance::GlobalMeasured',
  'heuristic': 'Provenance::Heuristic',
  'baseline': 'Provenance::Baseline',
  'none': 'Provenance::None',
}

/** Serialise a string for a Rust string literal — JSON escaping matches Rust. */
function rustStr(s: string): string {
  return JSON.stringify(s)
}

function rustOptStr(s: string | null): string {
  return s === null ? 'None' : `Some(${rustStr(s)})`
}

function rustOptU16(n: number | null): string {
  return n === null ? 'None' : `Some(${n})`
}

const HEADER = `//! Generated by \`pipeline/lib/gen-sources-rs.ts\` — DO NOT EDIT MANUALLY.
//!
//! Rust mirror of \`pipeline/lib/sources.ts\`. Regenerate via:
//!
//! \`\`\`bash
//! cd pipeline && npm run gen:sources
//! \`\`\`
//!
//! This file is committed to git (no \`build.rs\` / node dependency in the
//! Rust build — plan v5 /gg W: keep noise-compute a pure-Rust crate).

use serde::{Deserialize, Serialize};

/// How authoritative a dataset is. Must stay aligned with the TypeScript
/// \`Provenance\` union in \`pipeline/lib/sources.ts\`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Provenance {
    #[serde(rename = "national-measured")]
    NationalMeasured,
    #[serde(rename = "continental-measured")]
    ContinentalMeasured,
    #[serde(rename = "global-measured")]
    GlobalMeasured,
    #[serde(rename = "heuristic")]
    Heuristic,
    #[serde(rename = "baseline")]
    Baseline,
    #[serde(rename = "none")]
    None,
}

impl Provenance {
    /// Ranking for overwrite decisions. Higher wins. Mirrors
    /// \`pipeline/lib/sources.ts::PROVENANCE_RANK\`.
    pub fn rank(self) -> u8 {
        match self {
            Self::NationalMeasured => 5,
            Self::ContinentalMeasured => 4,
            Self::GlobalMeasured => 3,
            Self::Heuristic => 2,
            Self::Baseline => 1,
            Self::None => 0,
        }
    }

    /// Stable string form for logging and JSON — matches the TypeScript union.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::NationalMeasured => "national-measured",
            Self::ContinentalMeasured => "continental-measured",
            Self::GlobalMeasured => "global-measured",
            Self::Heuristic => "heuristic",
            Self::Baseline => "baseline",
            Self::None => "none",
        }
    }

    /// True if this source represents real measured data (national,
    /// continental or global-scale observational). Used by \`access_factor\`
    /// to pass through measured AADT without re-applying access multipliers
    /// (the measurement already reflects the restriction).
    pub fn is_measured(self) -> bool {
        matches!(
            self,
            Self::NationalMeasured | Self::ContinentalMeasured | Self::GlobalMeasured
        )
    }

    /// True if the row carries any enricher-written data (anything except
    /// the \`None\` sentinel). Equivalent to the legacy \`traffic_source > 0\`
    /// check, derivable from \`dataset_id\` via \`provenance_of()\`.
    pub fn has_data(self) -> bool {
        !matches!(self, Self::None)
    }

    /// Legacy string form for the JSON API contract
    /// (\`frontend/src/types/noise.ts::traffic_source\` union). Folds the six
    /// Provenance variants into the three strings the frontend currently
    /// understands. When F.4 lands (ts-rs derivation), the frontend will
    /// switch to the full \`as_str()\` form and this helper goes away.
    pub fn legacy_traffic_source_str(self) -> &'static str {
        match self {
            Self::NationalMeasured | Self::ContinentalMeasured | Self::GlobalMeasured => {
                "matched_external"
            }
            Self::Heuristic => "estimated_service_tree",
            Self::Baseline | Self::None => "default_by_class",
        }
    }
}

/// One enrichment dataset. Mirrors the TypeScript \`Source\` interface.
#[derive(Debug, Clone, Copy)]
pub struct Source {
    pub id: u16,
    pub key: &'static str,
    pub provenance: Provenance,
    pub layer: &'static str,
    pub name: &'static str,
    pub license: Option<&'static str>,
    pub url: Option<&'static str>,
    pub year: Option<u16>,
}

impl Source {
    /// Sentinel "unspecified" entry used for pre-provenance rows (id = 0).
    pub const UNSPECIFIED: Source = SOURCES[0];
}

/// Fixed source id for the single aircraft observational dataset
/// (\`global-adsb-planet\`). Avoids scattering the magic literal \`1\`
/// across every aircraft writer / reader.
pub const AIRCRAFT_ADSB_SOURCE_ID: u16 = 1;

/// Binary search by id — SOURCES is emitted sorted by id (generator
/// preserves TS \`DATASETS\` order, which is id-ascending). Called per
/// road / rail / industrial row in pipeline-worker + source-reader hot
/// paths, so O(log N) beats the previous O(N).
pub fn get_source(id: u16) -> Option<&'static Source> {
    SOURCES
        .binary_search_by_key(&id, |s| s.id)
        .ok()
        .map(|idx| &SOURCES[idx])
}

/// Shorthand for the common "what's the provenance of this stamp" lookup.
pub fn provenance_of(id: u16) -> Provenance {
    get_source(id).map_or(Provenance::None, |s| s.provenance)
}
`

const entries = SOURCES.map((s) => {
  return `    Source {
        id: ${s.id},
        key: ${rustStr(s.key)},
        provenance: ${PROVENANCE_TO_RUST[s.provenance]},
        layer: ${rustStr(s.layer)},
        name: ${rustStr(s.name)},
        license: ${rustOptStr(s.license)},
        url: ${rustOptStr(s.url)},
        year: ${rustOptU16(s.year)},
    },`
}).join('\n')

const output = `${HEADER}
pub const SOURCES: &[Source] = &[
${entries}
];
`

writeFileSync(OUTPUT_PATH, output)
console.log(
  `✓ Generated ${OUTPUT_PATH} with ${SOURCES.length} entries ` +
    `(${output.length.toLocaleString()} bytes).`,
)
