/**
 * Unified provenance registry — single source of truth for noise-dataset
 * provenance across roads, railways, buildings, industrial and aircraft.
 *
 * This file layers a `Provenance` classification on top of the existing
 * `DATASETS` array from `enrichment-datasets.ts`. It is the *authoritative*
 * registry for the engine (Rust mirror is generated by
 * `scripts/gen-sources-rs.ts`) and for future arrow schema v5 (`source_id`).
 *
 * Design notes:
 *   - `Provenance` replaces the numeric `priority` as the driver of
 *     overwrite decisions. Rank is derived from the enum, not a bare
 *     integer, so engine code can branch on measured vs heuristic without
 *     a registry lookup on every segment.
 *   - Tie-break: newer `year` wins, then higher `id` as deterministic
 *     fallback. (Plan v5 /gg DeepSeek W3 — quality proxy by year.)
 *   - Idempotent re-run semantics preserved (`existingId === selfId` →
 *     overwrite). (Plan v5 /gg Gemini C2.)
 *
 * Until Commit 0.3 lands (arrow `source_id` schema), per-layer
 * `<layer>_dataset_id` columns continue to store the same numeric ids —
 * only the overwrite logic and the Rust-visible `Provenance` classification
 * change.
 */

import { DATASETS, type Dataset } from './enrichment-datasets.js'

// ═══════════════════════════════════════════════════════════════════════════
// Provenance enum + rank
// ═══════════════════════════════════════════════════════════════════════════

/**
 * How authoritative the data is.
 *
 *   - `national-measured`     — per-segment spatial or ref match against a
 *                               national authority's published measurement
 *                               (ŘSD, BASt, MITMA, DNIT, FHWA HPMS, DOH, …).
 *   - `continental-measured`  — per-segment harmonised measurement across
 *                               multiple countries (EU CityTraffic, E-PRTR,
 *                               continental GTFS).
 *   - `global-measured`       — per-facility observational dataset with
 *                               global reach (GPPD power plants, USWTDB
 *                               wind turbines, ADS-B aircraft).
 *   - `heuristic`             — model-computed estimate (service-tree flow
 *                               accumulation, NACE name-keyword match).
 *   - `baseline`              — OSM-only inference or global baseline
 *                               coverage (Overture buildings, Copernicus
 *                               DEM, OSM tag-only fallback).
 *   - `none`                  — sentinel for unenriched rows (id = 0).
 */
export type Provenance =
  | 'national-measured'
  | 'continental-measured'
  | 'global-measured'
  | 'heuristic'
  | 'baseline'
  | 'none'

/**
 * Lexicographic rank for `shouldOverwrite`. Higher rank wins.
 *
 * Tiers roughly mirror the legacy `priority` scale (80/70/50/10/0) but use
 * an enum so engine code can branch cleanly (measured → skip access_factor;
 * heuristic → apply access_factor; none → engine-side default cascade).
 */
export const PROVENANCE_RANK: Record<Provenance, number> = {
  'national-measured': 5,
  'continental-measured': 4,
  'global-measured': 3,
  'heuristic': 2,
  'baseline': 1,
  'none': 0,
}

// ═══════════════════════════════════════════════════════════════════════════
// Source interface + registry
// ═══════════════════════════════════════════════════════════════════════════

export interface Source {
  id: number            // u16, globally unique, never recycled
  key: string           // stable slug ('cz-rsd', 'br-dnit', ...)
  provenance: Provenance
  layer: Dataset['layer']  // roads | railways | buildings | industrial | any
  name: string
  license: string | null
  url: string | null
  year: number | null   // used for same-rank tiebreak (newer wins)
}

/**
 * Derive a `Provenance` label from the legacy `priority` field plus a
 * couple of per-key manual overrides for ambiguous tier-50 entries.
 *
 * Mapping:
 *   priority 80 → national-measured
 *   priority 70 → continental-measured
 *   priority 50 → global-measured, except global-overture / *copernicus*
 *                 which are OSM-derived / baseline rasters (baseline)
 *   priority 10 → heuristic
 *   priority 0  → none (sentinel)
 *   other       → none (defensive for malformed entries)
 *
 * Keep this function deterministic — it is exercised by the Rust codegen
 * script (`scripts/gen-sources-rs.ts`) and by the `shouldOverwrite`
 * tiebreak path.
 */
function provenanceFromEntry(d: Dataset): Provenance {
  if (d.id === 0) return 'none'
  if (d.priority >= 80) return 'national-measured'
  if (d.priority >= 70) return 'continental-measured'
  if (d.priority >= 50) {
    // tier-50 has three members today: GPPD (measured per-facility),
    // Overture buildings (OSM-derived inference), Copernicus DEM (global
    // raster baseline). Only GPPD qualifies as "measured".
    if (d.key.includes('overture')) return 'baseline'
    if (d.key.includes('copernicus')) return 'baseline'
    return 'global-measured'
  }
  if (d.priority >= 10) return 'heuristic'
  return 'none'
}

/** The unified SOURCES array — one entry per dataset, with derived provenance. */
export const SOURCES: readonly Source[] = DATASETS.map<Source>((d) => ({
  id: d.id,
  key: d.key,
  provenance: provenanceFromEntry(d),
  layer: d.layer,
  name: d.name,
  license: d.license,
  url: d.url,
  year: d.year,
}))

export const SOURCES_BY_ID = new Map<number, Source>(SOURCES.map((s) => [s.id, s]))
export const SOURCES_BY_KEY = new Map<string, Source>(SOURCES.map((s) => [s.key, s]))

/** The sentinel "unspecified" entry (always id = 0). */
export const UNSPECIFIED: Source = SOURCES_BY_ID.get(0)!

// ═══════════════════════════════════════════════════════════════════════════
// Overwrite decision
// ═══════════════════════════════════════════════════════════════════════════

/**
 * Returns `true` if a write stamped by `newId` should replace the row's
 * current `existingId`.
 *
 * Rules (in priority order):
 *   1. Empty slot (existing = 0) → overwrite
 *   2. Idempotent re-run (existing = self) → overwrite (safe — same source)
 *   3. Unknown id in registry → overwrite (defensive: treat as legacy)
 *   4. Higher provenance rank wins
 *   5. Same rank: newer `year` wins
 *   6. Same rank + same year (or any null): higher id wins (deterministic)
 *
 * (Plan v5 /gg Gemini C2 idempotent early return; DeepSeek W3 year before id.)
 */
export function shouldOverwrite(existingId: number, newId: number): boolean {
  if (existingId === 0 || existingId === newId) return true
  const a = SOURCES_BY_ID.get(existingId)
  const b = SOURCES_BY_ID.get(newId)
  if (!a || !b) return true
  const rA = PROVENANCE_RANK[a.provenance]
  const rB = PROVENANCE_RANK[b.provenance]
  if (rB !== rA) return rB > rA
  if (a.year !== null && b.year !== null && a.year !== b.year) return b.year > a.year
  return b.id > a.id
}
