//! Generated by `pipeline/lib/gen-sources-rs.ts` — DO NOT EDIT MANUALLY.
//!
//! Rust mirror of `pipeline/lib/sources.ts`. Regenerate via:
//!
//! ```bash
//! cd pipeline && npm run gen:sources
//! ```
//!
//! This file is committed to git (no `build.rs` / node dependency in the
//! Rust build — plan v5 /gg W: keep noise-compute a pure-Rust crate).

use serde::{Deserialize, Serialize};

/// How authoritative a dataset is. Must stay aligned with the TypeScript
/// `Provenance` union in `pipeline/lib/sources.ts`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum Provenance {
    #[serde(rename = "national-measured")]
    NationalMeasured,
    #[serde(rename = "continental-measured")]
    ContinentalMeasured,
    #[serde(rename = "global-measured")]
    GlobalMeasured,
    #[serde(rename = "heuristic")]
    Heuristic,
    #[serde(rename = "baseline")]
    Baseline,
    #[serde(rename = "none")]
    None,
}

impl Provenance {
    /// Ranking for overwrite decisions. Higher wins. Mirrors
    /// `pipeline/lib/sources.ts::PROVENANCE_RANK`.
    pub fn rank(self) -> u8 {
        match self {
            Self::NationalMeasured => 5,
            Self::ContinentalMeasured => 4,
            Self::GlobalMeasured => 3,
            Self::Heuristic => 2,
            Self::Baseline => 1,
            Self::None => 0,
        }
    }

    /// Stable string form for logging and JSON — matches the TypeScript union.
    pub fn as_str(self) -> &'static str {
        match self {
            Self::NationalMeasured => "national-measured",
            Self::ContinentalMeasured => "continental-measured",
            Self::GlobalMeasured => "global-measured",
            Self::Heuristic => "heuristic",
            Self::Baseline => "baseline",
            Self::None => "none",
        }
    }

    /// True if this source represents real measured data (national,
    /// continental or global-scale observational). Used by `access_factor`
    /// to pass through measured AADT without re-applying access multipliers
    /// (the measurement already reflects the restriction).
    pub fn is_measured(self) -> bool {
        matches!(
            self,
            Self::NationalMeasured | Self::ContinentalMeasured | Self::GlobalMeasured
        )
    }

    /// True if the row carries any enricher-written data (anything except
    /// the `None` sentinel). Equivalent to the legacy `traffic_source > 0`
    /// check, derivable from `dataset_id` via `provenance_of()`.
    pub fn has_data(self) -> bool {
        !matches!(self, Self::None)
    }

    /// Legacy string form for the JSON API contract
    /// (`frontend/src/types/noise.ts::traffic_source` union). Folds the six
    /// Provenance variants into the three strings the frontend currently
    /// understands. When F.4 lands (ts-rs derivation), the frontend will
    /// switch to the full `as_str()` form and this helper goes away.
    pub fn legacy_traffic_source_str(self) -> &'static str {
        match self {
            Self::NationalMeasured | Self::ContinentalMeasured | Self::GlobalMeasured => {
                "matched_external"
            }
            Self::Heuristic => "estimated_service_tree",
            Self::Baseline | Self::None => "default_by_class",
        }
    }
}

/// One enrichment dataset. Mirrors the TypeScript `Source` interface.
#[derive(Debug, Clone, Copy)]
pub struct Source {
    pub id: u16,
    pub key: &'static str,
    pub provenance: Provenance,
    pub layer: &'static str,
    pub name: &'static str,
    pub license: Option<&'static str>,
    pub url: Option<&'static str>,
    pub year: Option<u16>,
}

impl Source {
    /// Sentinel "unspecified" entry used for pre-provenance rows (id = 0).
    pub const UNSPECIFIED: Source = SOURCES[0];
}

/// Fixed source id for the single aircraft observational dataset
/// (`global-adsb-planet`). Avoids scattering the magic literal `1`
/// across every aircraft writer / reader.
pub const AIRCRAFT_ADSB_SOURCE_ID: u16 = 1;

/// Binary search by id — SOURCES is emitted sorted by id (generator
/// preserves TS `DATASETS` order, which is id-ascending). Called per
/// road / rail / industrial row in pipeline-worker + source-reader hot
/// paths, so O(log N) beats the previous O(N).
pub fn get_source(id: u16) -> Option<&'static Source> {
    SOURCES
        .binary_search_by_key(&id, |s| s.id)
        .ok()
        .map(|idx| &SOURCES[idx])
}

/// Shorthand for the common "what's the provenance of this stamp" lookup.
pub fn provenance_of(id: u16) -> Provenance {
    get_source(id).map_or(Provenance::None, |s| s.provenance)
}

pub const SOURCES: &[Source] = &[
    Source {
        id: 0,
        key: "unspecified",
        provenance: Provenance::None,
        layer: "any",
        name: "Unspecified / pre-provenance legacy",
        license: None,
        url: None,
        year: None,
    },
    Source {
        id: 1,
        key: "global-adsb-planet",
        provenance: Provenance::GlobalMeasured,
        layer: "aircraft",
        name: "ADSBexchange planet TAR archives",
        license: Some("CC-BY-SA-4.0"),
        url: Some("https://www.adsbexchange.com/"),
        year: Some(2024),
    },
    Source {
        id: 10,
        key: "eu-city-traffic",
        provenance: Provenance::ContinentalMeasured,
        layer: "roads",
        name: "EU Harmonized Traffic Volumes (Nature Scientific Data)",
        license: Some("CC-BY-4.0"),
        url: Some("https://github.com/XavB64/traffic-volume-data-EU-cities"),
        year: Some(2023),
    },
    Source {
        id: 11,
        key: "service-tree-heuristic",
        provenance: Provenance::Heuristic,
        layer: "roads",
        name: "Service-tree residential flow heuristic",
        license: Some("project-internal"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 20,
        key: "cz-rsd-scitani",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "ŘSD Celostátní sčítání dopravy",
        license: Some("CC-BY-4.0"),
        url: Some("https://geoportal.rsd.cz/"),
        year: Some(2020),
    },
    Source {
        id: 21,
        key: "us-fhwa-hpms",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "FHWA Highway Performance Monitoring System",
        license: Some("public-domain"),
        url: Some("https://www.fhwa.dot.gov/policyinformation/hpms.cfm"),
        year: Some(2022),
    },
    Source {
        id: 22,
        key: "de-bast-autobahn",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "BASt SVZ Autobahnen",
        license: Some("DL-DE BY 2.0"),
        url: Some("https://www.bast.de/"),
        year: Some(2021),
    },
    Source {
        id: 23,
        key: "de-bast-bundesstrassen",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "BASt SVZ Bundesstraßen",
        license: Some("DL-DE BY 2.0"),
        url: Some("https://www.bast.de/"),
        year: Some(2021),
    },
    Source {
        id: 24,
        key: "fr-cerema-tmja",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Cerema Trafic Moyen Journalier Annuel",
        license: Some("etalab-2.0"),
        url: Some("https://www.data.gouv.fr/"),
        year: Some(2024),
    },
    Source {
        id: 100,
        key: "global-gtfs-transit",
        provenance: Provenance::ContinentalMeasured,
        layer: "railways",
        name: "Continental GTFS transit feeds (aggregated; mostly Europe + AU/IN)",
        license: Some("mixed (per-operator)"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 110,
        key: "cz-szcd-gtfs",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Správa železnic GTFS",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.spravazeleznic.cz/"),
        year: Some(2025),
    },
    Source {
        id: 200,
        key: "cz-ruian-vfr",
        provenance: Provenance::NationalMeasured,
        layer: "buildings",
        name: "ČÚZK RÚIAN VFR",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.cuzk.cz/Uvod/Produkty-a-sluzby/RUIAN/"),
        year: Some(2024),
    },
    Source {
        id: 201,
        key: "es-catastro",
        provenance: Provenance::NationalMeasured,
        layer: "buildings",
        name: "Dirección General del Catastro",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.catastro.minhap.es/"),
        year: Some(2024),
    },
    Source {
        id: 300,
        key: "global-gppd",
        provenance: Provenance::GlobalMeasured,
        layer: "industrial",
        name: "Global Power Plant Database",
        license: Some("CC-BY-4.0"),
        url: Some("https://datasets.wri.org/dataset/globalpowerplantdatabase"),
        year: Some(2021),
    },
    Source {
        id: 301,
        key: "global-uswtdb",
        provenance: Provenance::NationalMeasured,
        layer: "industrial",
        name: "US Wind Turbine Database",
        license: Some("public-domain"),
        url: Some("https://eerscmap.usgs.gov/uswtdb/"),
        year: Some(2024),
    },
    Source {
        id: 310,
        key: "europe-eprtr",
        provenance: Provenance::ContinentalMeasured,
        layer: "industrial",
        name: "European Pollutant Release and Transfer Register",
        license: Some("CC-BY-4.0"),
        url: Some("https://industry.eea.europa.eu/"),
        year: Some(2022),
    },
    Source {
        id: 320,
        key: "cz-irz",
        provenance: Provenance::NationalMeasured,
        layer: "industrial",
        name: "ČHMÚ Integrovaný registr znečišťování",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.irz.cz/"),
        year: Some(2023),
    },
    Source {
        id: 330,
        key: "global-industrial-national-mix",
        provenance: Provenance::Heuristic,
        layer: "industrial",
        name: "OSM-derived per-country industrial (may include GEM/GPPD/USWTDB matches)",
        license: Some("ODbL-1.0"),
        url: Some("https://www.openstreetmap.org/"),
        year: Some(2025),
    },
    Source {
        id: 1004,
        key: "ar-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DNV TMDA 2017-18 + IGN GeoServer",
        license: Some("public-data"),
        url: Some("https://ide.transporte.gob.ar/geoserver/observ/ows"),
        year: Some(2018),
    },
    Source {
        id: 1013,
        key: "bo-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "ABC Red Vial Fundamental (community ArcGIS mirror)",
        license: Some("community-mirror"),
        url: Some("https://services2.arcgis.com/1GTOs4RWV6SKu0wr/"),
        year: Some(2024),
    },
    Source {
        id: 1014,
        key: "br-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DNIT Rodovias Federais",
        license: Some("public-data"),
        url: Some("https://www.dnit.gov.br/"),
        year: Some(2017),
    },
    Source {
        id: 1019,
        key: "ca-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Quebec MTQ DJMA",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.donneesquebec.ca/recherche/dataset/debit-de-circulation"),
        year: Some(2024),
    },
    Source {
        id: 1023,
        key: "cl-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MOP Vialidad Red Vial + Plan Nacional de Censos TMDA",
        license: Some("public-data"),
        url: Some("https://rest-sit.mop.gob.cl/"),
        year: Some(2025),
    },
    Source {
        id: 1025,
        key: "cn-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "China Highway Network (ArcGIS mirror) + tier defaults",
        license: Some("community-mirror"),
        url: Some("https://services1.arcgis.com/ERdCHt0sNM6dENSD/"),
        year: Some(2024),
    },
    Source {
        id: 1026,
        key: "co-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "INVIAS Red Vial Nacional + TPDS_NUBE TPDA",
        license: Some("public-data"),
        url: Some("https://services6.arcgis.com/kyerLIHvrND0OSya/"),
        year: Some(2024),
    },
    Source {
        id: 1031,
        key: "dk-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Vejdirektoratet Mastra",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.opendata.dk/vejdirektoratet/taellinger-nogletal-mastra"),
        year: Some(2025),
    },
    Source {
        id: 1034,
        key: "ec-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "CONGOPE Red Vial Ecuador (ArcGIS mirror)",
        license: Some("public-data"),
        url: Some("https://services6.arcgis.com/pYn2F4v1aESZqj1u/"),
        year: Some(2024),
    },
    Source {
        id: 1037,
        key: "es-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MITMA Mapa de Tráfico",
        license: Some("CC-BY-4.0"),
        url: Some("https://mapatrafico.transportes.gob.es/"),
        year: Some(2022),
    },
    Source {
        id: 1039,
        key: "fi-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Väylävirasto Liikennemäärät",
        license: Some("CC-BY-4.0"),
        url: Some("https://avoindata.suomi.fi/data/fi/dataset/liikennemaarat"),
        year: Some(2024),
    },
    Source {
        id: 1041,
        key: "gb-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DfT AADF (Annual Average Daily Flow)",
        license: Some("Open Government Licence v3.0"),
        url: Some("https://roadtraffic.dft.gov.uk/"),
        year: Some(2024),
    },
    Source {
        id: 1048,
        key: "id-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Bina Marga GIS (PUPR) — Jalan Daerah + Nasional + Tol",
        license: Some("public-data"),
        url: Some("https://gisportal.binamarga.pu.go.id/"),
        year: Some(2024),
    },
    Source {
        id: 1049,
        key: "ie-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "TII Counter Sites + Daily Class Aggregate",
        license: Some("CC-BY-4.0"),
        url: Some("https://data.tii.ie/"),
        year: Some(2020),
    },
    Source {
        id: 1050,
        key: "in-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Bharatmala Road Network (Esri Living Atlas India)",
        license: Some("public-data"),
        url: Some("https://livingatlas.esri.in/"),
        year: Some(2024),
    },
    Source {
        id: 1054,
        key: "it-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "Anas TGM (Traffico Giornaliero Medio)",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.stradeanas.it/"),
        year: Some(2024),
    },
    Source {
        id: 1088,
        key: "no-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "NVDB Trafikkmengde (Statens vegvesen)",
        license: Some("NLOD 2.0"),
        url: Some("https://nvdbapiles.atlas.vegvesen.no/"),
        year: Some(2025),
    },
    Source {
        id: 1090,
        key: "nz-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "NZTA Carriageway + Auckland Transport AADT",
        license: Some("CC-BY-4.0"),
        url: Some("https://opendata-nzta.opendata.arcgis.com/"),
        year: Some(2024),
    },
    Source {
        id: 1093,
        key: "pe-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MTC Provías Red Vial Nacional + dIMD (ArcGIS mirror)",
        license: Some("public-data"),
        url: Some("https://services6.arcgis.com/G8JFnqCHKQ9vb8YW/"),
        year: Some(2024),
    },
    Source {
        id: 1095,
        key: "ph-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DPWH Road Classification (ArcGIS)",
        license: Some("public-data"),
        url: Some("https://services1.arcgis.com/IwZZTMxZCmAmFYvF/"),
        year: Some(2026),
    },
    Source {
        id: 1097,
        key: "pl-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "GDDKiA Generalny Pomiar Ruchu (GPR)",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.gov.pl/web/gddkia/generalny-pomiar-ruchu-20202021"),
        year: Some(2021),
    },
    Source {
        id: 1098,
        key: "py-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MOPC Rutas Nacionales (KMZ)",
        license: Some("public-data"),
        url: Some("https://www.mopc.gov.py/red-vial/"),
        year: Some(2023),
    },
    Source {
        id: 1102,
        key: "sa-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "MoT count stations + Riyadh PMS + SA Interactive Atlas",
        license: Some("open-data"),
        url: Some("https://mot.gov.sa/en/open-data"),
        year: Some(2024),
    },
    Source {
        id: 1113,
        key: "th-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "DRR Rural Roads AADT (MOT CKAN mirror) + DOH defaults",
        license: Some("public-data"),
        url: Some("https://datagov.mot.go.th/"),
        year: Some(2024),
    },
    Source {
        id: 1124,
        key: "ve-national-roads",
        provenance: Provenance::NationalMeasured,
        layer: "roads",
        name: "VE360 Vialidad (SIGOT community mirror)",
        license: Some("community-mirror"),
        url: Some("https://services6.arcgis.com/lpJCO3ug8HhNiEOV/"),
        year: Some(2019),
    },
    Source {
        id: 2000,
        key: "ae-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Dubai RTA unified GTFS (via Dubai Pulse)",
        license: Some("open-data"),
        url: Some("https://www.dubaipulse.gov.ae/"),
        year: Some(2025),
    },
    Source {
        id: 2004,
        key: "ar-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "IGN GeoServer (Trenes Argentinos + Subte BA)",
        license: Some("public-data"),
        url: Some("https://wms.ign.gob.ar/geoserver/transporte/ows"),
        year: Some(2024),
    },
    Source {
        id: 2005,
        key: "au-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Australian state rail GTFS (TfNSW + Transperth + Adelaide Metro)",
        license: Some("CC-BY-4.0"),
        url: Some("https://opendata.transport.nsw.gov.au/"),
        year: Some(2025),
    },
    Source {
        id: 2009,
        key: "be-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Belgian urban rail GTFS (STIB/MIVB + De Lijn + TEC)",
        license: Some("open-data"),
        url: Some("https://stibmivb.opendatasoft.com/"),
        year: Some(2025),
    },
    Source {
        id: 2015,
        key: "ca-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Canadian rail GTFS (VIA Rail + Metrolinx + TTC + STM + TransLink + OC Transpo + Calgary + ETS)",
        license: Some("open-data"),
        url: Some("https://www.viarail.ca/"),
        year: Some(2025),
    },
    Source {
        id: 2021,
        key: "cn-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Mainland CR + Metros (ArcGIS FeatureServer mirror)",
        license: Some("community-mirror"),
        url: Some("https://services7.arcgis.com/m6uLpqj7MgjPU371/"),
        year: Some(2024),
    },
    Source {
        id: 2024,
        key: "dk-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Rejseplanen unified GTFS",
        license: Some("open-data"),
        url: Some("https://www.rejseplanen.info/labs/GTFS.zip"),
        year: Some(2025),
    },
    Source {
        id: 2028,
        key: "es-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Renfe + FGC GTFS",
        license: Some("CC-BY-4.0"),
        url: Some("https://data.renfe.com/"),
        year: Some(2025),
    },
    Source {
        id: 2030,
        key: "fi-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Finnish rail GTFS (Fintraffic VR + HSL + Tampere Raitiotie)",
        license: Some("CC-BY-4.0"),
        url: Some("https://rata.digitraffic.fi/"),
        year: Some(2025),
    },
    Source {
        id: 2035,
        key: "ie-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "NTA Transport for Ireland unified GTFS",
        license: Some("open-data"),
        url: Some("https://www.transportforireland.ie/"),
        year: Some(2025),
    },
    Source {
        id: 2036,
        key: "il-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Israeli MoT unified GTFS",
        license: Some("CC-BY-4.0"),
        url: Some("https://www.gov.il/he/pages/gtfs_general_transit_feed_specifications"),
        year: Some(2025),
    },
    Source {
        id: 2037,
        key: "in-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Living Atlas IN Railway Network",
        license: Some("public-data"),
        url: Some("https://livingatlas.esri.in/"),
        year: Some(2024),
    },
    Source {
        id: 2040,
        key: "it-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Italian regional rail GTFS (Trenitalia + Trenord + GTT + Ferrotramviaria)",
        license: Some("CC-BY-4.0"),
        url: Some("https://dati.toscana.it/"),
        year: Some(2025),
    },
    Source {
        id: 2044,
        key: "kr-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "KORAIL operator-class CNOSSOS defaults",
        license: Some("derived-from-OSM"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 2057,
        key: "mx-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "CDMX SEMOVI unified GTFS",
        license: Some("open-data"),
        url: Some("https://datos.cdmx.gob.mx/dataset/gtfs"),
        year: Some(2025),
    },
    Source {
        id: 2066,
        key: "pl-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Polish Trains unified GTFS (Kuranowski/PKP PLK)",
        license: Some("CC-BY-4.0"),
        url: Some("https://mkuran.pl/gtfs/"),
        year: Some(2025),
    },
    Source {
        id: 2067,
        key: "pt-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Portuguese rail GTFS (CP + Metro do Porto + MTS)",
        license: Some("open-data"),
        url: Some("https://publico.cp.pt/gtfs"),
        year: Some(2025),
    },
    Source {
        id: 2073,
        key: "se-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "GTFS Sverige 2 unified (Trafiklab/Samtrafiken)",
        license: Some("open-data"),
        url: Some("https://www.trafiklab.se/"),
        year: Some(2025),
    },
    Source {
        id: 2075,
        key: "th-national-railway",
        provenance: Provenance::NationalMeasured,
        layer: "railways",
        name: "Namtang GTFS (Thailand)",
        license: Some("open-data"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 9000,
        key: "industrial-name-heuristic",
        provenance: Provenance::Heuristic,
        layer: "industrial",
        name: "OSM industrial name-keyword NACE heuristic",
        license: Some("project-internal"),
        url: None,
        year: Some(2025),
    },
    Source {
        id: 9001,
        key: "global-overture",
        provenance: Provenance::Baseline,
        layer: "buildings",
        name: "Overture Maps buildings (MS/Google/Meta)",
        license: Some("CDLA-Permissive-2.0"),
        url: Some("https://overturemaps.org/"),
        year: Some(2024),
    },
    Source {
        id: 9002,
        key: "global-copernicus-glo30",
        provenance: Provenance::Baseline,
        layer: "any",
        name: "Copernicus GLO-30 DEM",
        license: Some("CC-BY-4.0"),
        url: Some("https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model"),
        year: Some(2021),
    },
];
